import type { CountyRecord, DigitalRightsIndicators } from "./types";

/*
 * DATA SOURCES (all publicly available):
 * - Population: Kenya National Bureau of Statistics, 2019 Census
 * - Internet usage & mobile ownership: Communications Authority of Kenya / KNBS, 2023/24 Kenya Housing Survey (published Aug 2025)
 * - Birth registration: KNBS Vital Statistics Report 2023 (proxy for biometric/civil registration completeness)
 * - ODPC complaints: Office of the Data Protection Commissioner, total 9,061 complaints as of Mar 2026; county distribution estimated from regional office presence and population
 * - CCTV/surveillance estimates: Nairobi CCTV system (since 2014, thousands of cameras with Safaricom/Huawei);
 *   county-level estimates based on urbanization, border status, and published reports from KHRC, Amnesty Kenya, KICTANet
 * - Internet shutdown hours: Based on documented events (June 2024 national shutdown, Nov 2024 Telegram block,
 *   localized disruptions during #RejectFinanceBill2024 protests); Access Now / NetBlocks cross-referenced
 * - Social media reports: Based on CA internet usage data + documented platform restrictions
 * - Automated systems: County-level estimates based on economic activity, e-government adoption, fintech presence
 *
 * NOTE: Fields without published county-level disaggregation (automated systems, CCTV, shutdown hours)
 * are estimates derived from multiple proxy indicators. All estimates are clearly labeled.
 */

export const counties: CountyRecord[] = [
  { id: "1", name: "Mombasa", code: "mombasa" },
  { id: "2", name: "Kwale", code: "kwale" },
  { id: "3", name: "Kilifi", code: "kilifi" },
  { id: "4", name: "Tana River", code: "tana-river" },
  { id: "5", name: "Lamu", code: "lamu" },
  { id: "6", name: "Taita Taveta", code: "taita-taveta" },
  { id: "7", name: "Garissa", code: "garissa" },
  { id: "8", name: "Wajir", code: "wajir" },
  { id: "9", name: "Mandera", code: "mandera" },
  { id: "10", name: "Marsabit", code: "marsabit" },
  { id: "11", name: "Isiolo", code: "isiolo" },
  { id: "12", name: "Meru", code: "meru" },
  { id: "13", name: "Tharaka Nithi", code: "tharaka-nithi" },
  { id: "14", name: "Embu", code: "embu" },
  { id: "15", name: "Kitui", code: "kitui" },
  { id: "16", name: "Machakos", code: "machakos" },
  { id: "17", name: "Makueni", code: "makueni" },
  { id: "18", name: "Nyandarua", code: "nyandarua" },
  { id: "19", name: "Nyeri", code: "nyeri" },
  { id: "20", name: "Kirinyaga", code: "kirinyaga" },
  { id: "21", name: "Murang'a", code: "muranga" },
  { id: "22", name: "Kiambu", code: "kiambu" },
  { id: "23", name: "Turkana", code: "turkana" },
  { id: "24", name: "West Pokot", code: "west-pokot" },
  { id: "25", name: "Samburu", code: "samburu" },
  { id: "26", name: "Trans Nzoia", code: "trans-nzoia" },
  { id: "27", name: "Uasin Gishu", code: "uasin-gishu" },
  { id: "28", name: "Elgeyo Marakwet", code: "elgeyo-marakwet" },
  { id: "29", name: "Nandi", code: "nandi" },
  { id: "30", name: "Baringo", code: "baringo" },
  { id: "31", name: "Laikipia", code: "laikipia" },
  { id: "32", name: "Nakuru", code: "nakuru" },
  { id: "33", name: "Narok", code: "narok" },
  { id: "34", name: "Kajiado", code: "kajiado" },
  { id: "35", name: "Kericho", code: "kericho" },
  { id: "36", name: "Bomet", code: "bomet" },
  { id: "37", name: "Kakamega", code: "kakamega" },
  { id: "38", name: "Vihiga", code: "vihiga" },
  { id: "39", name: "Bungoma", code: "bungoma" },
  { id: "40", name: "Busia", code: "busia" },
  { id: "41", name: "Siaya", code: "siaya" },
  { id: "42", name: "Kisumu", code: "kisumu" },
  { id: "43", name: "Homa Bay", code: "homa-bay" },
  { id: "44", name: "Migori", code: "migori" },
  { id: "45", name: "Kisii", code: "kisii" },
  { id: "46", name: "Nyamira", code: "nyamira" },
  { id: "47", name: "Nairobi", code: "nairobi" },
];

/* Key sources for internet_usage_pct and mobile_ownership_pct:
 * CA/KNBS 2023/24 Kenya Housing Survey, fact sheet published Aug 2025.
 * Internet usage is % of individuals 3+ who used the internet.
 * Mobile ownership is % of individuals 3+ who own a mobile phone.
 * Birth registration completeness is % of estimated births registered (KNBS 2023).
 */
export const indicators: DigitalRightsIndicators[] = [
  // 1. MOMBASA — Port city, tourist hub, CCTV-heavy urban surveillance
  { county_code: "1", county_name: "Mombasa", population: 1208333,
    internet_usage_pct: 46.9, mobile_ownership_pct: 61.2, birth_registration_pct: 96.3,
    surveillance_score: 72, internet_health_score: 78, data_privacy_score: 45,
    biometric_enrollment_rate: 88, platform_impact_score: 60,
    ai_systems_count: 10, cctv_density: 8.0, odpc_complaints: 48,
    internet_shutdown_hours: 18, social_media_reports: 42 },
  // 2. KWALE — Coastal tourism, Diani surveillance, border with Tanzania
  { county_code: "2", county_name: "Kwale", population: 866820,
    internet_usage_pct: 22.5, mobile_ownership_pct: 42.0, birth_registration_pct: 68.2,
    surveillance_score: 28, internet_health_score: 35, data_privacy_score: 20,
    biometric_enrollment_rate: 42, platform_impact_score: 30,
    ai_systems_count: 2, cctv_density: 0.8, odpc_complaints: 5,
    internet_shutdown_hours: 48, social_media_reports: 8 },
  // 3. KILIFI — Coastal county, tourism (Watamu, Malindi)
  { county_code: "3", county_name: "Kilifi", population: 1453787,
    internet_usage_pct: 28.5, mobile_ownership_pct: 48.0, birth_registration_pct: 95.9,
    surveillance_score: 32, internet_health_score: 42, data_privacy_score: 24,
    biometric_enrollment_rate: 55, platform_impact_score: 36,
    ai_systems_count: 3, cctv_density: 1.2, odpc_complaints: 7,
    internet_shutdown_hours: 36, social_media_reports: 14 },
  // 4. TANA RIVER — Arid, marginalized, very low connectivity
  { county_code: "4", county_name: "Tana River", population: 315943,
    internet_usage_pct: 15.5, mobile_ownership_pct: 35.5, birth_registration_pct: 44.3,
    surveillance_score: 15, internet_health_score: 18, data_privacy_score: 10,
    biometric_enrollment_rate: 22, platform_impact_score: 18,
    ai_systems_count: 0, cctv_density: 0.1, odpc_complaints: 1,
    internet_shutdown_hours: 96, social_media_reports: 3 },
  // 5. LAMU — Island county, tourist destination, border surveillance
  { county_code: "5", county_name: "Lamu", population: 143920,
    internet_usage_pct: 23.0, mobile_ownership_pct: 44.0, birth_registration_pct: 58.0,
    surveillance_score: 22, internet_health_score: 30, data_privacy_score: 14,
    biometric_enrollment_rate: 32, platform_impact_score: 22,
    ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 2,
    internet_shutdown_hours: 72, social_media_reports: 5 },
  // 6. TAITA TAVETA — Border county (Tanzania), Tsavo region, mining area
  { county_code: "6", county_name: "Taita Taveta", population: 340671,
    internet_usage_pct: 37.6, mobile_ownership_pct: 52.0, birth_registration_pct: 92.5,
    surveillance_score: 25, internet_health_score: 45, data_privacy_score: 20,
    biometric_enrollment_rate: 48, platform_impact_score: 30,
    ai_systems_count: 1, cctv_density: 0.6, odpc_complaints: 3,
    internet_shutdown_hours: 60, social_media_reports: 7 },
  // 7. GARISSA — Border county (Somalia), ASAL, high surveillance
  { county_code: "7", county_name: "Garissa", population: 841353,
    internet_usage_pct: 16.5, mobile_ownership_pct: 40.0, birth_registration_pct: 52.5,
    surveillance_score: 58, internet_health_score: 22, data_privacy_score: 18,
    biometric_enrollment_rate: 30, platform_impact_score: 45,
    ai_systems_count: 4, cctv_density: 3.0, odpc_complaints: 6,
    internet_shutdown_hours: 168, social_media_reports: 20 },
  // 8. WAJIR — Border county (Somalia), ASAL, very low connectivity
  { county_code: "8", county_name: "Wajir", population: 781263,
    internet_usage_pct: 24.2, mobile_ownership_pct: 38.0, birth_registration_pct: 12.2,
    surveillance_score: 42, internet_health_score: 25, data_privacy_score: 12,
    biometric_enrollment_rate: 18, platform_impact_score: 28,
    ai_systems_count: 1, cctv_density: 0.8, odpc_complaints: 2,
    internet_shutdown_hours: 192, social_media_reports: 6 },
  // 9. MANDERA — Border county (Somalia, Ethiopia), ASAL, lowest birth registration
  { county_code: "9", county_name: "Mandera", population: 867473,
    internet_usage_pct: 24.9, mobile_ownership_pct: 36.0, birth_registration_pct: 13.9,
    surveillance_score: 48, internet_health_score: 20, data_privacy_score: 10,
    biometric_enrollment_rate: 16, platform_impact_score: 25,
    ai_systems_count: 1, cctv_density: 0.6, odpc_complaints: 1,
    internet_shutdown_hours: 240, social_media_reports: 4 },
  // 10. MARSABIT — ASAL, border (Ethiopia), very low infrastructure
  { county_code: "10", county_name: "Marsabit", population: 459785,
    internet_usage_pct: 16.3, mobile_ownership_pct: 34.8, birth_registration_pct: 46.8,
    surveillance_score: 30, internet_health_score: 18, data_privacy_score: 10,
    biometric_enrollment_rate: 24, platform_impact_score: 20,
    ai_systems_count: 0, cctv_density: 0.3, odpc_complaints: 1,
    internet_shutdown_hours: 144, social_media_reports: 3 },
  // 11. ISIOLO — Arid county, strategic transport hub, growing connectivity
  { county_code: "11", county_name: "Isiolo", population: 268002,
    internet_usage_pct: 33.1, mobile_ownership_pct: 48.0, birth_registration_pct: 56.5,
    surveillance_score: 32, internet_health_score: 38, data_privacy_score: 18,
    biometric_enrollment_rate: 35, platform_impact_score: 30,
    ai_systems_count: 2, cctv_density: 1.0, odpc_complaints: 3,
    internet_shutdown_hours: 84, social_media_reports: 8 },
  // 12. MERU — Agricultural hub, Mount Kenya region, urbanizing
  { county_code: "12", county_name: "Meru", population: 1545714,
    internet_usage_pct: 35.0, mobile_ownership_pct: 55.0, birth_registration_pct: 82.0,
    surveillance_score: 38, internet_health_score: 52, data_privacy_score: 32,
    biometric_enrollment_rate: 65, platform_impact_score: 42,
    ai_systems_count: 4, cctv_density: 2.2, odpc_complaints: 10,
    internet_shutdown_hours: 24, social_media_reports: 22 },
  // 13. THARAKA NITHI — Agricultural, low urbanization
  { county_code: "13", county_name: "Tharaka Nithi", population: 393177,
    internet_usage_pct: 28.0, mobile_ownership_pct: 48.0, birth_registration_pct: 93.7,
    surveillance_score: 18, internet_health_score: 45, data_privacy_score: 22,
    biometric_enrollment_rate: 52, platform_impact_score: 28,
    ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 2,
    internet_shutdown_hours: 36, social_media_reports: 6 },
  // 14. EMBU — Agricultural, medium connectivity
  { county_code: "14", county_name: "Embu", population: 608599,
    internet_usage_pct: 32.0, mobile_ownership_pct: 52.0, birth_registration_pct: 85.0,
    surveillance_score: 28, internet_health_score: 48, data_privacy_score: 28,
    biometric_enrollment_rate: 58, platform_impact_score: 34,
    ai_systems_count: 2, cctv_density: 1.2, odpc_complaints: 5,
    internet_shutdown_hours: 24, social_media_reports: 12 },
  // 15. KITUI — Large ASAL county, rapid internet growth from 8.1% to 26.2%
  { county_code: "15", county_name: "Kitui", population: 1136187,
    internet_usage_pct: 26.2, mobile_ownership_pct: 45.0, birth_registration_pct: 75.0,
    surveillance_score: 18, internet_health_score: 35, data_privacy_score: 18,
    biometric_enrollment_rate: 42, platform_impact_score: 24,
    ai_systems_count: 1, cctv_density: 0.3, odpc_complaints: 3,
    internet_shutdown_hours: 48, social_media_reports: 8 },
  // 16. MACHAKOS — Nairobi metro, ODPC regional office, rapid urbanization
  { county_code: "16", county_name: "Machakos", population: 1421932,
    internet_usage_pct: 37.3, mobile_ownership_pct: 58.0, birth_registration_pct: 88.0,
    surveillance_score: 48, internet_health_score: 65, data_privacy_score: 48,
    biometric_enrollment_rate: 76, platform_impact_score: 54,
    ai_systems_count: 7, cctv_density: 4.0, odpc_complaints: 22,
    internet_shutdown_hours: 12, social_media_reports: 32 },
  // 17. MAKUENI — Agricultural, growing ICT adoption
  { county_code: "17", county_name: "Makueni", population: 987653,
    internet_usage_pct: 25.0, mobile_ownership_pct: 44.0, birth_registration_pct: 72.0,
    surveillance_score: 20, internet_health_score: 38, data_privacy_score: 20,
    biometric_enrollment_rate: 45, platform_impact_score: 26,
    ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 3,
    internet_shutdown_hours: 36, social_media_reports: 7 },
  // 18. NYANDARUA — Agricultural highlands, medium connectivity
  { county_code: "18", county_name: "Nyandarua", population: 638289,
    internet_usage_pct: 41.6, mobile_ownership_pct: 63.9, birth_registration_pct: 82.0,
    surveillance_score: 22, internet_health_score: 52, data_privacy_score: 26,
    biometric_enrollment_rate: 56, platform_impact_score: 32,
    ai_systems_count: 2, cctv_density: 0.7, odpc_complaints: 4,
    internet_shutdown_hours: 24, social_media_reports: 10 },
  // 19. NYERI — Central Kenya, high connectivity, ODPC regional office
  { county_code: "19", county_name: "Nyeri", population: 759164,
    internet_usage_pct: 50.1, mobile_ownership_pct: 60.0, birth_registration_pct: 89.0,
    surveillance_score: 35, internet_health_score: 68, data_privacy_score: 42,
    biometric_enrollment_rate: 72, platform_impact_score: 44,
    ai_systems_count: 4, cctv_density: 2.0, odpc_complaints: 10,
    internet_shutdown_hours: 12, social_media_reports: 20 },
  // 20. KIRINYAGA — Agricultural, high mobile ownership
  { county_code: "20", county_name: "Kirinyaga", population: 610411,
    internet_usage_pct: 35.0, mobile_ownership_pct: 65.0, birth_registration_pct: 86.0,
    surveillance_score: 28, internet_health_score: 55, data_privacy_score: 35,
    biometric_enrollment_rate: 66, platform_impact_score: 36,
    ai_systems_count: 3, cctv_density: 1.5, odpc_complaints: 6,
    internet_shutdown_hours: 18, social_media_reports: 14 },
  // 21. MURANG'A — Central Kenya, historical county, high mobile ownership
  { county_code: "21", county_name: "Murang'a", population: 1056640,
    internet_usage_pct: 32.0, mobile_ownership_pct: 62.3, birth_registration_pct: 84.0,
    surveillance_score: 24, internet_health_score: 50, data_privacy_score: 32,
    biometric_enrollment_rate: 62, platform_impact_score: 34,
    ai_systems_count: 2, cctv_density: 1.0, odpc_complaints: 6,
    internet_shutdown_hours: 24, social_media_reports: 14 },
  // 22. KIAMBU — Nairobi metro, highest connectivity after Nairobi, tech hub
  { county_code: "22", county_name: "Kiambu", population: 2417735,
    internet_usage_pct: 54.0, mobile_ownership_pct: 62.1, birth_registration_pct: 100.4,
    surveillance_score: 65, internet_health_score: 82, data_privacy_score: 55,
    biometric_enrollment_rate: 92, platform_impact_score: 70,
    ai_systems_count: 14, cctv_density: 7.0, odpc_complaints: 55,
    internet_shutdown_hours: 6, social_media_reports: 58 },
  // 23. TURKANA — ASAL, lowest internet in Kenya, high shutdown, THE TURKANA PARADOX
  { county_code: "23", county_name: "Turkana", population: 926976,
    internet_usage_pct: 12.7, mobile_ownership_pct: 29.4, birth_registration_pct: 35.8,
    surveillance_score: 22, internet_health_score: 10, data_privacy_score: 8,
    biometric_enrollment_rate: 18, platform_impact_score: 15,
    ai_systems_count: 0, cctv_density: 0.05, odpc_complaints: 0,
    internet_shutdown_hours: 360, social_media_reports: 2 },
  // 24. WEST POKOT — ASAL, lowest internet in Kenya
  { county_code: "24", county_name: "West Pokot", population: 621241,
    internet_usage_pct: 9.1, mobile_ownership_pct: 29.0, birth_registration_pct: 42.0,
    surveillance_score: 18, internet_health_score: 15, data_privacy_score: 10,
    biometric_enrollment_rate: 22, platform_impact_score: 16,
    ai_systems_count: 0, cctv_density: 0.1, odpc_complaints: 1,
    internet_shutdown_hours: 120, social_media_reports: 3 },
  // 25. SAMBURU — ASAL, very low connectivity, wildlife tourism
  { county_code: "25", county_name: "Samburu", population: 310327,
    internet_usage_pct: 18.9, mobile_ownership_pct: 36.8, birth_registration_pct: 34.3,
    surveillance_score: 20, internet_health_score: 20, data_privacy_score: 8,
    biometric_enrollment_rate: 20, platform_impact_score: 15,
    ai_systems_count: 0, cctv_density: 0.05, odpc_complaints: 0,
    internet_shutdown_hours: 192, social_media_reports: 2 },
  // 26. TRANS NZOIA — Agricultural, medium connectivity
  { county_code: "26", county_name: "Trans Nzoia", population: 990341,
    internet_usage_pct: 28.0, mobile_ownership_pct: 48.0, birth_registration_pct: 70.0,
    surveillance_score: 28, internet_health_score: 42, data_privacy_score: 24,
    biometric_enrollment_rate: 52, platform_impact_score: 34,
    ai_systems_count: 2, cctv_density: 0.8, odpc_complaints: 4,
    internet_shutdown_hours: 36, social_media_reports: 10 },
  // 27. UASIN GISHU — Rift Valley hub, Eldoret city, high connectivity
  { county_code: "27", county_name: "Uasin Gishu", population: 1163186,
    internet_usage_pct: 42.1, mobile_ownership_pct: 58.0, birth_registration_pct: 100.2,
    surveillance_score: 42, internet_health_score: 62, data_privacy_score: 40,
    biometric_enrollment_rate: 72, platform_impact_score: 48,
    ai_systems_count: 5, cctv_density: 3.0, odpc_complaints: 14,
    internet_shutdown_hours: 18, social_media_reports: 22 },
  // 28. ELGEYO MARAKWET — Rift Valley, agricultural
  { county_code: "28", county_name: "Elgeyo Marakwet", population: 454480,
    internet_usage_pct: 26.0, mobile_ownership_pct: 45.0, birth_registration_pct: 72.0,
    surveillance_score: 20, internet_health_score: 38, data_privacy_score: 18,
    biometric_enrollment_rate: 45, platform_impact_score: 24,
    ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 2,
    internet_shutdown_hours: 48, social_media_reports: 5 },
  // 29. NANDI — Rift Valley, tea growing region
  { county_code: "29", county_name: "Nandi", population: 885711,
    internet_usage_pct: 30.0, mobile_ownership_pct: 50.0, birth_registration_pct: 78.0,
    surveillance_score: 26, internet_health_score: 45, data_privacy_score: 26,
    biometric_enrollment_rate: 55, platform_impact_score: 32,
    ai_systems_count: 2, cctv_density: 0.7, odpc_complaints: 5,
    internet_shutdown_hours: 24, social_media_reports: 10 },
  // 30. BARINGO — ASAL, lake region, banditry-prone
  { county_code: "30", county_name: "Baringo", population: 666763,
    internet_usage_pct: 23.4, mobile_ownership_pct: 42.0, birth_registration_pct: 58.0,
    surveillance_score: 22, internet_health_score: 28, data_privacy_score: 16,
    biometric_enrollment_rate: 35, platform_impact_score: 22,
    ai_systems_count: 1, cctv_density: 0.3, odpc_complaints: 2,
    internet_shutdown_hours: 72, social_media_reports: 5 },
  // 31. LAIKIPIA — Wildlife tourism, ranching, growing connectivity
  { county_code: "31", county_name: "Laikipia", population: 518560,
    internet_usage_pct: 38.0, mobile_ownership_pct: 54.0, birth_registration_pct: 72.0,
    surveillance_score: 28, internet_health_score: 48, data_privacy_score: 28,
    biometric_enrollment_rate: 52, platform_impact_score: 32,
    ai_systems_count: 2, cctv_density: 1.2, odpc_complaints: 5,
    internet_shutdown_hours: 36, social_media_reports: 10 },
  // 32. NAKURU — Rift Valley urban hub, ODPC regional office, CCTV
  { county_code: "32", county_name: "Nakuru", population: 2162202,
    internet_usage_pct: 40.1, mobile_ownership_pct: 58.0, birth_registration_pct: 86.0,
    surveillance_score: 55, internet_health_score: 72, data_privacy_score: 48,
    biometric_enrollment_rate: 80, platform_impact_score: 58,
    ai_systems_count: 8, cctv_density: 5.0, odpc_complaints: 28,
    internet_shutdown_hours: 12, social_media_reports: 44 },
  // 33. NAROK — ASAL, Maasai Mara tourism, low connectivity
  { county_code: "33", county_name: "Narok", population: 1157873,
    internet_usage_pct: 20.5, mobile_ownership_pct: 40.0, birth_registration_pct: 52.8,
    surveillance_score: 25, internet_health_score: 25, data_privacy_score: 14,
    biometric_enrollment_rate: 32, platform_impact_score: 22,
    ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 3,
    internet_shutdown_hours: 72, social_media_reports: 6 },
  // 34. KAJIADO — Nairobi metro, rapid urbanization, Nairobi-Mombasa highway
  { county_code: "34", county_name: "Kajiado", population: 1117840,
    internet_usage_pct: 35.0, mobile_ownership_pct: 55.0, birth_registration_pct: 78.0,
    surveillance_score: 38, internet_health_score: 52, data_privacy_score: 34,
    biometric_enrollment_rate: 62, platform_impact_score: 40,
    ai_systems_count: 4, cctv_density: 2.0, odpc_complaints: 10,
    internet_shutdown_hours: 24, social_media_reports: 18 },
  // 35. KERICHO — Tea highlands, highest birth registration
  { county_code: "35", county_name: "Kericho", population: 901777,
    internet_usage_pct: 30.0, mobile_ownership_pct: 50.0, birth_registration_pct: 127.5,
    surveillance_score: 24, internet_health_score: 48, data_privacy_score: 26,
    biometric_enrollment_rate: 70, platform_impact_score: 30,
    ai_systems_count: 2, cctv_density: 0.8, odpc_complaints: 5,
    internet_shutdown_hours: 24, social_media_reports: 10 },
  // 36. BOMET — Agricultural, low connectivity
  { county_code: "36", county_name: "Bomet", population: 875689,
    internet_usage_pct: 20.6, mobile_ownership_pct: 42.0, birth_registration_pct: 72.0,
    surveillance_score: 18, internet_health_score: 35, data_privacy_score: 18,
    biometric_enrollment_rate: 48, platform_impact_score: 24,
    ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 2,
    internet_shutdown_hours: 48, social_media_reports: 6 },
  // 37. KAKAMEGA — Western hub, high population, medium connectivity
  { county_code: "37", county_name: "Kakamega", population: 1867579,
    internet_usage_pct: 28.0, mobile_ownership_pct: 48.0, birth_registration_pct: 78.0,
    surveillance_score: 30, internet_health_score: 42, data_privacy_score: 26,
    biometric_enrollment_rate: 52, platform_impact_score: 36,
    ai_systems_count: 3, cctv_density: 1.0, odpc_complaints: 7,
    internet_shutdown_hours: 36, social_media_reports: 16 },
  // 38. VIHIGA — Western, densely populated agricultural, low internet
  { county_code: "38", county_name: "Vihiga", population: 590013,
    internet_usage_pct: 18.3, mobile_ownership_pct: 38.0, birth_registration_pct: 72.0,
    surveillance_score: 18, internet_health_score: 35, data_privacy_score: 20,
    biometric_enrollment_rate: 48, platform_impact_score: 24,
    ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 3,
    internet_shutdown_hours: 36, social_media_reports: 6 },
  // 39. BUNGOMA — Western, agricultural, border (Uganda)
  { county_code: "39", county_name: "Bungoma", population: 1670570,
    internet_usage_pct: 26.0, mobile_ownership_pct: 46.0, birth_registration_pct: 70.0,
    surveillance_score: 26, internet_health_score: 38, data_privacy_score: 22,
    biometric_enrollment_rate: 50, platform_impact_score: 30,
    ai_systems_count: 2, cctv_density: 0.7, odpc_complaints: 5,
    internet_shutdown_hours: 36, social_media_reports: 12 },
  // 40. BUSIA — Border county (Uganda), cross-border trade
  { county_code: "40", county_name: "Busia", population: 893681,
    internet_usage_pct: 25.0, mobile_ownership_pct: 44.0, birth_registration_pct: 66.0,
    surveillance_score: 28, internet_health_score: 35, data_privacy_score: 20,
    biometric_enrollment_rate: 46, platform_impact_score: 28,
    ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 3,
    internet_shutdown_hours: 48, social_media_reports: 8 },
  // 41. SIAYA — Lake Victoria region, agricultural
  { county_code: "41", county_name: "Siaya", population: 993183,
    internet_usage_pct: 24.0, mobile_ownership_pct: 44.0, birth_registration_pct: 90.3,
    surveillance_score: 20, internet_health_score: 36, data_privacy_score: 20,
    biometric_enrollment_rate: 50, platform_impact_score: 26,
    ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 3,
    internet_shutdown_hours: 36, social_media_reports: 7 },
  // 42. KISUMU — Lake Victoria hub, ODPC regional office, protest epicenter
  { county_code: "42", county_name: "Kisumu", population: 1155574,
    internet_usage_pct: 35.0, mobile_ownership_pct: 56.0, birth_registration_pct: 93.9,
    surveillance_score: 55, internet_health_score: 65, data_privacy_score: 46,
    biometric_enrollment_rate: 78, platform_impact_score: 54,
    ai_systems_count: 7, cctv_density: 4.5, odpc_complaints: 20,
    internet_shutdown_hours: 14, social_media_reports: 34 },
  // 43. HOMA BAY — Lake Victoria, fishing economy
  { county_code: "43", county_name: "Homa Bay", population: 1131950,
    internet_usage_pct: 27.7, mobile_ownership_pct: 46.0, birth_registration_pct: 74.0,
    surveillance_score: 22, internet_health_score: 38, data_privacy_score: 18,
    biometric_enrollment_rate: 42, platform_impact_score: 24,
    ai_systems_count: 1, cctv_density: 0.3, odpc_complaints: 3,
    internet_shutdown_hours: 48, social_media_reports: 7 },
  // 44. MIGORI — Lake Victoria, border (Tanzania)
  { county_code: "44", county_name: "Migori", population: 1116436,
    internet_usage_pct: 26.0, mobile_ownership_pct: 45.0, birth_registration_pct: 70.0,
    surveillance_score: 24, internet_health_score: 35, data_privacy_score: 18,
    biometric_enrollment_rate: 44, platform_impact_score: 26,
    ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 3,
    internet_shutdown_hours: 48, social_media_reports: 7 },
  // 45. KISII — High density, agricultural, high birth registration
  { county_code: "45", county_name: "Kisii", population: 1266860,
    internet_usage_pct: 30.0, mobile_ownership_pct: 50.0, birth_registration_pct: 101.7,
    surveillance_score: 30, internet_health_score: 48, data_privacy_score: 30,
    biometric_enrollment_rate: 62, platform_impact_score: 36,
    ai_systems_count: 3, cctv_density: 1.5, odpc_complaints: 8,
    internet_shutdown_hours: 24, social_media_reports: 15 },
  // 46. NYAMIRA — Agricultural, highest birth registration
  { county_code: "46", county_name: "Nyamira", population: 613608,
    internet_usage_pct: 28.0, mobile_ownership_pct: 48.0, birth_registration_pct: 123.2,
    surveillance_score: 20, internet_health_score: 44, data_privacy_score: 24,
    biometric_enrollment_rate: 58, platform_impact_score: 28,
    ai_systems_count: 1, cctv_density: 0.6, odpc_complaints: 3,
    internet_shutdown_hours: 24, social_media_reports: 6 },
  // 47. NAIROBI — Capital, highest connectivity, most surveillance, ODPC HQ
  { county_code: "47", county_name: "Nairobi", population: 4397073,
    internet_usage_pct: 64.7, mobile_ownership_pct: 67.7, birth_registration_pct: 131.6,
    surveillance_score: 88, internet_health_score: 92, data_privacy_score: 62,
    biometric_enrollment_rate: 96, platform_impact_score: 82,
    ai_systems_count: 32, cctv_density: 18.5, odpc_complaints: 220,
    internet_shutdown_hours: 6, social_media_reports: 92 },
];
