import type { CountyRecord, DigitalRightsIndicators } from "./types";

export const counties: CountyRecord[] = [
  { id: "1", name: "Mombasa", code: "mombasa" },
  { id: "2", name: "Kwale", code: "kwale" },
  { id: "3", name: "Kilifi", code: "kilifi" },
  { id: "4", name: "Tana River", code: "tana-river" },
  { id: "5", name: "Lamu", code: "lamu" },
  { id: "6", name: "Taita Taveta", code: "taita-taveta" },
  { id: "7", name: "Garissa", code: "garissa" },
  { id: "8", name: "Wajir", code: "wajir" },
  { id: "9", name: "Mandera", code: "mandera" },
  { id: "10", name: "Marsabit", code: "marsabit" },
  { id: "11", name: "Isiolo", code: "isiolo" },
  { id: "12", name: "Meru", code: "meru" },
  { id: "13", name: "Tharaka Nithi", code: "tharaka-nithi" },
  { id: "14", name: "Embu", code: "embu" },
  { id: "15", name: "Kitui", code: "kitui" },
  { id: "16", name: "Machakos", code: "machakos" },
  { id: "17", name: "Makueni", code: "makueni" },
  { id: "18", name: "Nyandarua", code: "nyandarua" },
  { id: "19", name: "Nyeri", code: "nyeri" },
  { id: "20", name: "Kirinyaga", code: "kirinyaga" },
  { id: "21", name: "Murang'a", code: "muranga" },
  { id: "22", name: "Kiambu", code: "kiambu" },
  { id: "23", name: "Turkana", code: "turkana" },
  { id: "24", name: "West Pokot", code: "west-pokot" },
  { id: "25", name: "Samburu", code: "samburu" },
  { id: "26", name: "Trans Nzoia", code: "trans-nzoia" },
  { id: "27", name: "Uasin Gishu", code: "uasin-gishu" },
  { id: "28", name: "Elgeyo Marakwet", code: "elgeyo-marakwet" },
  { id: "29", name: "Nandi", code: "nandi" },
  { id: "30", name: "Baringo", code: "baringo" },
  { id: "31", name: "Laikipia", code: "laikipia" },
  { id: "32", name: "Nakuru", code: "nakuru" },
  { id: "33", name: "Narok", code: "narok" },
  { id: "34", name: "Kajiado", code: "kajiado" },
  { id: "35", name: "Kericho", code: "kericho" },
  { id: "36", name: "Bomet", code: "bomet" },
  { id: "37", name: "Kakamega", code: "kakamega" },
  { id: "38", name: "Vihiga", code: "vihiga" },
  { id: "39", name: "Bungoma", code: "bungoma" },
  { id: "40", name: "Busia", code: "busia" },
  { id: "41", name: "Siaya", code: "siaya" },
  { id: "42", name: "Kisumu", code: "kisumu" },
  { id: "43", name: "Homa Bay", code: "homa-bay" },
  { id: "44", name: "Migori", code: "migori" },
  { id: "45", name: "Kisii", code: "kisii" },
  { id: "46", name: "Nyamira", code: "nyamira" },
  { id: "47", name: "Nairobi", code: "nairobi" },
];

export const indicators: DigitalRightsIndicators[] = [
  { county_code: "1", county_name: "Mombasa", population: 1200000, surveillance_score: 72, internet_health_score: 85, data_privacy_score: 45, biometric_enrollment_rate: 88, platform_impact_score: 60, ai_systems_count: 12, cctv_density: 8.5, odpc_complaints: 34, internet_shutdown_hours: 12, social_media_reports: 45 },
  { county_code: "2", county_name: "Kwale", population: 450000, surveillance_score: 25, internet_health_score: 60, data_privacy_score: 22, biometric_enrollment_rate: 42, platform_impact_score: 35, ai_systems_count: 2, cctv_density: 0.8, odpc_complaints: 3, internet_shutdown_hours: 48, social_media_reports: 8 },
  { county_code: "3", county_name: "Kilifi", population: 550000, surveillance_score: 30, internet_health_score: 55, data_privacy_score: 25, biometric_enrollment_rate: 50, platform_impact_score: 40, ai_systems_count: 3, cctv_density: 1.2, odpc_complaints: 5, internet_shutdown_hours: 36, social_media_reports: 12 },
  { county_code: "4", county_name: "Tana River", population: 320000, surveillance_score: 15, internet_health_score: 30, data_privacy_score: 12, biometric_enrollment_rate: 28, platform_impact_score: 20, ai_systems_count: 0, cctv_density: 0.1, odpc_complaints: 1, internet_shutdown_hours: 96, social_media_reports: 3 },
  { county_code: "5", county_name: "Lamu", population: 140000, surveillance_score: 20, internet_health_score: 40, data_privacy_score: 15, biometric_enrollment_rate: 35, platform_impact_score: 25, ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 2, internet_shutdown_hours: 72, social_media_reports: 5 },
  { county_code: "6", county_name: "Taita Taveta", population: 180000, surveillance_score: 22, internet_health_score: 50, data_privacy_score: 18, biometric_enrollment_rate: 40, platform_impact_score: 28, ai_systems_count: 1, cctv_density: 0.6, odpc_complaints: 2, internet_shutdown_hours: 60, social_media_reports: 6 },
  { county_code: "7", county_name: "Garissa", population: 480000, surveillance_score: 55, internet_health_score: 25, data_privacy_score: 20, biometric_enrollment_rate: 32, platform_impact_score: 50, ai_systems_count: 4, cctv_density: 3.2, odpc_complaints: 8, internet_shutdown_hours: 120, social_media_reports: 22 },
  { county_code: "8", county_name: "Wajir", population: 380000, surveillance_score: 35, internet_health_score: 20, data_privacy_score: 14, biometric_enrollment_rate: 25, platform_impact_score: 30, ai_systems_count: 1, cctv_density: 0.8, odpc_complaints: 2, internet_shutdown_hours: 168, social_media_reports: 7 },
  { county_code: "9", county_name: "Mandera", population: 420000, surveillance_score: 40, internet_health_score: 15, data_privacy_score: 10, biometric_enrollment_rate: 22, platform_impact_score: 28, ai_systems_count: 1, cctv_density: 0.6, odpc_complaints: 1, internet_shutdown_hours: 240, social_media_reports: 4 },
  { county_code: "10", county_name: "Marsabit", population: 310000, surveillance_score: 28, internet_health_score: 25, data_privacy_score: 12, biometric_enrollment_rate: 30, platform_impact_score: 22, ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 1, internet_shutdown_hours: 144, social_media_reports: 3 },
  { county_code: "11", county_name: "Isiolo", population: 170000, surveillance_score: 30, internet_health_score: 35, data_privacy_score: 18, biometric_enrollment_rate: 38, platform_impact_score: 30, ai_systems_count: 2, cctv_density: 1.0, odpc_complaints: 3, internet_shutdown_hours: 84, social_media_reports: 8 },
  { county_code: "12", county_name: "Meru", population: 660000, surveillance_score: 40, internet_health_score: 65, data_privacy_score: 35, biometric_enrollment_rate: 65, platform_impact_score: 45, ai_systems_count: 5, cctv_density: 2.5, odpc_complaints: 12, internet_shutdown_hours: 24, social_media_reports: 28 },
  { county_code: "13", county_name: "Tharaka Nithi", population: 200000, surveillance_score: 20, internet_health_score: 55, data_privacy_score: 25, biometric_enrollment_rate: 55, platform_impact_score: 30, ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 2, internet_shutdown_hours: 36, social_media_reports: 6 },
  { county_code: "14", county_name: "Embu", population: 260000, surveillance_score: 30, internet_health_score: 60, data_privacy_score: 30, biometric_enrollment_rate: 60, platform_impact_score: 35, ai_systems_count: 3, cctv_density: 1.5, odpc_complaints: 6, internet_shutdown_hours: 24, social_media_reports: 14 },
  { county_code: "15", county_name: "Kitui", population: 530000, surveillance_score: 18, internet_health_score: 40, data_privacy_score: 20, biometric_enrollment_rate: 45, platform_impact_score: 25, ai_systems_count: 1, cctv_density: 0.3, odpc_complaints: 4, internet_shutdown_hours: 48, social_media_reports: 9 },
  { county_code: "16", county_name: "Machakos", population: 550000, surveillance_score: 45, internet_health_score: 75, data_privacy_score: 50, biometric_enrollment_rate: 78, platform_impact_score: 55, ai_systems_count: 8, cctv_density: 4.5, odpc_complaints: 22, internet_shutdown_hours: 12, social_media_reports: 36 },
  { county_code: "17", county_name: "Makueni", population: 310000, surveillance_score: 20, internet_health_score: 50, data_privacy_score: 22, biometric_enrollment_rate: 48, platform_impact_score: 28, ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 3, internet_shutdown_hours: 36, social_media_reports: 7 },
  { county_code: "18", county_name: "Nyandarua", population: 250000, surveillance_score: 22, internet_health_score: 55, data_privacy_score: 28, biometric_enrollment_rate: 58, platform_impact_score: 32, ai_systems_count: 2, cctv_density: 0.7, odpc_complaints: 4, internet_shutdown_hours: 24, social_media_reports: 10 },
  { county_code: "19", county_name: "Nyeri", population: 350000, surveillance_score: 35, internet_health_score: 70, data_privacy_score: 45, biometric_enrollment_rate: 72, platform_impact_score: 45, ai_systems_count: 4, cctv_density: 2.0, odpc_complaints: 10, internet_shutdown_hours: 12, social_media_reports: 20 },
  { county_code: "20", county_name: "Kirinyaga", population: 280000, surveillance_score: 28, internet_health_score: 65, data_privacy_score: 38, biometric_enrollment_rate: 68, platform_impact_score: 38, ai_systems_count: 3, cctv_density: 1.8, odpc_complaints: 7, internet_shutdown_hours: 18, social_media_reports: 15 },
  { county_code: "21", county_name: "Murang'a", population: 370000, surveillance_score: 25, internet_health_score: 60, data_privacy_score: 35, biometric_enrollment_rate: 62, platform_impact_score: 35, ai_systems_count: 2, cctv_density: 1.2, odpc_complaints: 8, internet_shutdown_hours: 24, social_media_reports: 16 },
  { county_code: "22", county_name: "Kiambu", population: 920000, surveillance_score: 65, internet_health_score: 88, data_privacy_score: 55, biometric_enrollment_rate: 90, platform_impact_score: 70, ai_systems_count: 15, cctv_density: 7.5, odpc_complaints: 45, internet_shutdown_hours: 6, social_media_reports: 62 },
  { county_code: "23", county_name: "Turkana", population: 420000, surveillance_score: 22, internet_health_score: 10, data_privacy_score: 8, biometric_enrollment_rate: 18, platform_impact_score: 15, ai_systems_count: 0, cctv_density: 0.05, odpc_complaints: 0, internet_shutdown_hours: 360, social_media_reports: 2 },
  { county_code: "24", county_name: "West Pokot", population: 210000, surveillance_score: 18, internet_health_score: 20, data_privacy_score: 10, biometric_enrollment_rate: 25, platform_impact_score: 18, ai_systems_count: 0, cctv_density: 0.1, odpc_complaints: 1, internet_shutdown_hours: 120, social_media_reports: 3 },
  { county_code: "25", county_name: "Samburu", population: 160000, surveillance_score: 20, internet_health_score: 15, data_privacy_score: 8, biometric_enrollment_rate: 20, platform_impact_score: 15, ai_systems_count: 0, cctv_density: 0.05, odpc_complaints: 0, internet_shutdown_hours: 192, social_media_reports: 2 },
  { county_code: "26", county_name: "Trans Nzoia", population: 380000, surveillance_score: 30, internet_health_score: 55, data_privacy_score: 28, biometric_enrollment_rate: 58, platform_impact_score: 38, ai_systems_count: 2, cctv_density: 1.0, odpc_complaints: 5, internet_shutdown_hours: 36, social_media_reports: 12 },
  { county_code: "27", county_name: "Uasin Gishu", population: 430000, surveillance_score: 42, internet_health_score: 68, data_privacy_score: 40, biometric_enrollment_rate: 72, platform_impact_score: 48, ai_systems_count: 5, cctv_density: 3.0, odpc_complaints: 14, internet_shutdown_hours: 18, social_media_reports: 24 },
  { county_code: "28", county_name: "Elgeyo Marakwet", population: 200000, surveillance_score: 22, internet_health_score: 45, data_privacy_score: 20, biometric_enrollment_rate: 48, platform_impact_score: 25, ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 2, internet_shutdown_hours: 48, social_media_reports: 5 },
  { county_code: "29", county_name: "Nandi", population: 340000, surveillance_score: 28, internet_health_score: 58, data_privacy_score: 30, biometric_enrollment_rate: 60, platform_impact_score: 35, ai_systems_count: 2, cctv_density: 0.8, odpc_complaints: 6, internet_shutdown_hours: 24, social_media_reports: 11 },
  { county_code: "30", county_name: "Baringo", population: 250000, surveillance_score: 20, internet_health_score: 35, data_privacy_score: 18, biometric_enrollment_rate: 38, platform_impact_score: 22, ai_systems_count: 1, cctv_density: 0.3, odpc_complaints: 2, internet_shutdown_hours: 72, social_media_reports: 5 },
  { county_code: "31", county_name: "Laikipia", population: 200000, surveillance_score: 28, internet_health_score: 50, data_privacy_score: 30, biometric_enrollment_rate: 55, platform_impact_score: 32, ai_systems_count: 2, cctv_density: 1.2, odpc_complaints: 5, internet_shutdown_hours: 36, social_media_reports: 10 },
  { county_code: "32", county_name: "Nakuru", population: 840000, surveillance_score: 55, internet_health_score: 78, data_privacy_score: 50, biometric_enrollment_rate: 82, platform_impact_score: 60, ai_systems_count: 10, cctv_density: 5.5, odpc_complaints: 28, internet_shutdown_hours: 12, social_media_reports: 48 },
  { county_code: "33", county_name: "Narok", population: 420000, surveillance_score: 25, internet_health_score: 30, data_privacy_score: 15, biometric_enrollment_rate: 35, platform_impact_score: 22, ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 3, internet_shutdown_hours: 72, social_media_reports: 6 },
  { county_code: "34", county_name: "Kajiado", population: 380000, surveillance_score: 35, internet_health_score: 55, data_privacy_score: 35, biometric_enrollment_rate: 65, platform_impact_score: 40, ai_systems_count: 4, cctv_density: 2.0, odpc_complaints: 10, internet_shutdown_hours: 24, social_media_reports: 18 },
  { county_code: "35", county_name: "Kericho", population: 320000, surveillance_score: 25, internet_health_score: 55, data_privacy_score: 28, biometric_enrollment_rate: 58, platform_impact_score: 32, ai_systems_count: 2, cctv_density: 0.9, odpc_complaints: 5, internet_shutdown_hours: 24, social_media_reports: 10 },
  { county_code: "36", county_name: "Bomet", population: 240000, surveillance_score: 20, internet_health_score: 45, data_privacy_score: 20, biometric_enrollment_rate: 50, platform_impact_score: 25, ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 2, internet_shutdown_hours: 48, social_media_reports: 6 },
  { county_code: "37", county_name: "Kakamega", population: 690000, surveillance_score: 32, internet_health_score: 50, data_privacy_score: 28, biometric_enrollment_rate: 55, platform_impact_score: 38, ai_systems_count: 3, cctv_density: 1.0, odpc_complaints: 8, internet_shutdown_hours: 36, social_media_reports: 18 },
  { county_code: "38", county_name: "Vihiga", population: 150000, surveillance_score: 20, internet_health_score: 50, data_privacy_score: 25, biometric_enrollment_rate: 52, platform_impact_score: 28, ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 3, internet_shutdown_hours: 24, social_media_reports: 6 },
  { county_code: "39", county_name: "Bungoma", population: 520000, surveillance_score: 28, internet_health_score: 48, data_privacy_score: 22, biometric_enrollment_rate: 52, platform_impact_score: 32, ai_systems_count: 2, cctv_density: 0.7, odpc_complaints: 5, internet_shutdown_hours: 36, social_media_reports: 12 },
  { county_code: "40", county_name: "Busia", population: 310000, surveillance_score: 25, internet_health_score: 42, data_privacy_score: 20, biometric_enrollment_rate: 48, platform_impact_score: 28, ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 3, internet_shutdown_hours: 48, social_media_reports: 8 },
  { county_code: "41", county_name: "Siaya", population: 360000, surveillance_score: 22, internet_health_score: 45, data_privacy_score: 22, biometric_enrollment_rate: 50, platform_impact_score: 28, ai_systems_count: 1, cctv_density: 0.4, odpc_complaints: 4, internet_shutdown_hours: 36, social_media_reports: 8 },
  { county_code: "42", county_name: "Kisumu", population: 560000, surveillance_score: 55, internet_health_score: 72, data_privacy_score: 48, biometric_enrollment_rate: 80, platform_impact_score: 55, ai_systems_count: 8, cctv_density: 4.8, odpc_complaints: 20, internet_shutdown_hours: 12, social_media_reports: 35 },
  { county_code: "43", county_name: "Homa Bay", population: 340000, surveillance_score: 22, internet_health_score: 35, data_privacy_score: 18, biometric_enrollment_rate: 42, platform_impact_score: 25, ai_systems_count: 1, cctv_density: 0.3, odpc_complaints: 3, internet_shutdown_hours: 48, social_media_reports: 7 },
  { county_code: "44", county_name: "Migori", population: 350000, surveillance_score: 24, internet_health_score: 38, data_privacy_score: 20, biometric_enrollment_rate: 45, platform_impact_score: 28, ai_systems_count: 1, cctv_density: 0.5, odpc_complaints: 4, internet_shutdown_hours: 48, social_media_reports: 8 },
  { county_code: "45", county_name: "Kisii", population: 430000, surveillance_score: 30, internet_health_score: 58, data_privacy_score: 32, biometric_enrollment_rate: 62, platform_impact_score: 38, ai_systems_count: 3, cctv_density: 1.5, odpc_complaints: 8, internet_shutdown_hours: 24, social_media_reports: 16 },
  { county_code: "46", county_name: "Nyamira", population: 180000, surveillance_score: 22, internet_health_score: 52, data_privacy_score: 25, biometric_enrollment_rate: 55, platform_impact_score: 28, ai_systems_count: 1, cctv_density: 0.6, odpc_complaints: 3, internet_shutdown_hours: 24, social_media_reports: 6 },
  { county_code: "47", county_name: "Nairobi", population: 2980000, surveillance_score: 88, internet_health_score: 92, data_privacy_score: 60, biometric_enrollment_rate: 95, platform_impact_score: 82, ai_systems_count: 35, cctv_density: 18.5, odpc_complaints: 120, internet_shutdown_hours: 4, social_media_reports: 95 },
];
