'use client';
import { useSearchParams } from 'next/navigation';
import { counties, indicators } from '@/lib/data';
import { computeDRRS } from '@/lib/scoring';
import { Suspense } from 'react';

function BriefContent() {
  const searchParams = useSearchParams();
  const countyId = searchParams.get('id') || '47';
  const county = counties.find(c => c.id === countyId);

  if (!county) return <div className="p-8">County not found.</div>;

  const indicator = indicators.find(i => i.county_code === countyId);
  if (!indicator) return <div className="p-8">County data not found.</div>;

  const score = computeDRRS(county.id, indicator);

  return (
    <div className="max-w-4xl mx-auto p-8 bg-white text-[#292524] print:p-0 print:w-full">
      <div className="flex justify-between items-end border-b-4 border-[#78350F] pb-4 mb-8">
        <div>
          <h1 className="text-4xl font-bold text-[#78350F]">{county.name} County</h1>
          <h2 className="text-xl text-[#EA580C] mt-2">Digital Rights & Surveillance Brief</h2>
        </div>
        <button
          onClick={() => window.print()}
          className="print:hidden px-4 py-2 bg-[#78350F] text-[#FDFBF7] rounded hover:bg-[#92400E] transition"
        >
          Print Brief
        </button>
      </div>

      <div className="mb-8">
        <div className={`inline-block px-4 py-1 rounded-full font-bold text-lg ${score.drrs >= 70 ? 'bg-[#8C2D04] text-white' : score.drrs >= 50 ? 'bg-[#D95F0E] text-white' : score.drrs >= 30 ? 'bg-[#FEC44F] text-[#292524]' : 'bg-[#FFF7BC] text-[#292524]'}`}>
          DRRS: {score.drrs}/100 &mdash; {score.drrs >= 70 ? 'High Risk' : score.drrs >= 50 ? 'Elevated Risk' : score.drrs >= 30 ? 'Moderate Risk' : 'Lower Risk'}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-8">
        <div className="p-6 bg-[#F8F5F0] rounded-lg border border-[#E0DBD0]">
          <h3 className="font-bold text-[#6B6355] uppercase tracking-wide text-sm mb-2">Key Indicators</h3>
          <ul className="space-y-4">
            <li><strong>AI Systems Deployed:</strong> {indicator.ai_systems_count}</li>
            <li><strong>CCTV Density (per 10k):</strong> {indicator.cctv_density}</li>
            <li><strong>ODPC Complaints:</strong> {indicator.odpc_complaints}</li>
            <li><strong>Internet Shutdown Hrs:</strong> {indicator.internet_shutdown_hours}</li>
          </ul>
        </div>
        <div className="p-6 bg-[#F8F5F0] rounded-lg border border-[#E0DBD0]">
          <h3 className="font-bold text-[#6B6355] uppercase tracking-wide text-sm mb-2">Action Recommendations</h3>
          <ul className="list-disc pl-5 space-y-2 text-sm text-[#6B6355]">
            <li>Submit FOIA requests to county government regarding AI procurement.</li>
            <li>Engage local civil society on biometric inclusion campaigns.</li>
            <li>Monitor network throttling during localized protests.</li>
          </ul>
        </div>
      </div>

      <div className="space-y-3 mb-8">
        <h3 className="font-bold text-[#78350F]">DRRS Component Scores</h3>
        {[
          { label: 'Surveillance Density', value: score.surveillance },
          { label: 'Internet Health Risk', value: score.internetHealth },
          { label: 'Data Privacy Risk', value: score.dataPrivacy },
          { label: 'Biometric Enrollment', value: score.biometric },
          { label: 'Platform Impact', value: score.platformImpact },
        ].map((dim) => (
          <div key={dim.label} className="flex items-center gap-3">
            <span className="w-40 text-sm text-[#6B6355]">{dim.label}</span>
            <div className="flex-1 h-3 bg-[#E0DBD0] rounded-full overflow-hidden">
              <div
                className="h-full rounded-full transition-all"
                style={{
                  width: `${dim.value}%`,
                  backgroundColor: dim.value >= 70 ? '#8C2D04' : dim.value >= 50 ? '#D95F0E' : dim.value >= 30 ? '#FEC44F' : '#FFF7BC',
                }}
              />
            </div>
            <span className="w-8 text-right text-xs font-bold text-[#292524]">{dim.value}</span>
          </div>
        ))}
      </div>

      <p className="text-xs text-[#A8A08F] border-t border-[#E0DBD0] pt-4">
        Generated by the Kenya AI & Digital Rights Observatory. Data valid as of June 2026.
      </p>
    </div>
  );
}

export default function BriefPage() {
  return (
    <Suspense fallback={<div className="p-8">Loading brief...</div>}>
      <BriefContent />
    </Suspense>
  );
}
